export const colorOptions = [
        { value: '#FFFFFF', label: 'White' },
        { value: '#A30000', label: 'Dark Red' },
        { value: '#D20707', label: 'Red' },
        { value: '#FF0101', label: 'Bright Red' },
        { value: '#FF6D6D', label: 'Light Red' },
        { value: '#FF9C9C', label: 'Pink' },
        { value: '#FBC3C3', label: 'Very Light Pink' },
        { value: '#FFF1E3', label: 'Pale Yellow' },
        { value: '#4C00AF', label: 'Purple' },
        { value: '#6001DB', label: 'Deep Purple' },
        { value: '#903BFF', label: 'Lavender' },
        { value: '#B276FF', label: 'Light Lavender' },
        { value: '#CFAAFF', label: 'Mauve' },
        { value: '#E7D4FF', label: 'Light Lilac' },
        { value: '#FFD6AD', label: 'Peach' },
        { value: '#028336', label: 'Dark Green' },
        { value: '#00BE4C', label: 'Emerald Green' },
        { value: '#00E85D', label: 'Bright Green' },
        { value: '#58FF9B', label: 'Mint Green' },
        { value: '#A3FFC8', label: 'Light Mint' },
        { value: '#E1FFED', label: 'Pale Mint' },
        { value: '#FFB770', label: 'Light Orange' },
        { value: '#B48D01', label: 'Golden Yellow' },
        { value: '#E2B206', label: 'Yellow Gold' },
        { value: '#FFC700', label: 'Bright Yellow' },
        { value: '#FFDC5C', label: 'Goldenrod' },
        { value: '#FFE99A', label: 'Cream Yellow' },
        { value: '#FFF7DA', label: 'Soft Yellow' }
    ];